config/routes.rb
Rails.application.routes.draw do
  get 'stock/index'
  get 'search_stocks', to: "stock#search"

  root 'stock#index'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/stock.rb
class Stock < ApplicationRecord

  def self.find_by_ticker(ticker)
    where(ticker: ticker).first
  end

  def self.new_stock_lookup(ticker)
    looked_up_stock = StockQuote::Stock.quote(ticker)
    return nil unless looked_up_stock.name

    new_stock = new(ticker:looked_up_stock.symbol,
                      name:looked_up_stock.name,
             current_price:looked_up_stock.last_trade_price_only,
         one_year_estimate:looked_up_stock.oneyr_target_price,
            percent_change: (looked_up_stock.oneyr_target_price -
looked_up_stock.last_trade_price_only) / looked_up_stock.last_trade_price_only)
    new_stock
  end


  # new_stock = new(name: looked_up_stock.name)
  # new_stock.current_price = new_stock.last_trade_price_only
  # new_stock.one_year_estimate = new_stock.oneyr_target_price
  # new_stock.percent_change = (new_stock.one_year_estimate -
  #                            new_stock.current_price) / new_stock.current_price
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/stock_controller.rb
class StockController < ApplicationController
  def index

  end

  def search
    if params[:stock]
      @stock = Stock.find_by_ticker(params[:stock])
      @stock ||= Stock.new_stock_lookup(params[:stock])
    end

    if @stock
      render partial: 'lookup'
    else
      render status: :not_found, nothing: true
    end
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/stock_helper.rb
module StockHelper
end

app/views/common/_spinner.html.erb
<div id="spinner" class="row col-md-12 text-center spinner" style="display: none;">
  <i class="fa fa-spinner fa-spin fa-3x fa-fw"></i>Processing...
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="UTF-8" name="referrer" content="no-referrer">
    <meta http-equiv="X-UA-Compatible" content="IE=Edge,chrome=1">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title><%= content_for?(:title) ? yield(:title) : "FinalInvesting" %></title>
    <%= csrf_meta_tags %>


    <%= stylesheet_link_tag "application", :media => "all" %>

    <!-- For third-generation iPad with high-resolution Retina display: -->
    <!-- Size should be 144 x 144 pixels -->
    <%= favicon_link_tag 'apple-touch-icon-144x144-precomposed.png', :rel => 'apple-touch-icon-precomposed', :type => 'image/png', :sizes => '144x144' %>

    <!-- For iPhone with high-resolution Retina display: -->
    <!-- Size should be 114 x 114 pixels -->
    <%= favicon_link_tag 'apple-touch-icon-114x114-precomposed.png', :rel => 'apple-touch-icon-precomposed', :type => 'image/png', :sizes => '114x114' %>

    <!-- For first- and second-generation iPad: -->
    <!-- Size should be 72 x 72 pixels -->
    <%= favicon_link_tag 'apple-touch-icon-72x72-precomposed.png', :rel => 'apple-touch-icon-precomposed', :type => 'image/png', :sizes => '72x72' %>

    <!-- For non-Retina iPhone, iPod Touch, and Android 2.1+ devices: -->
    <!-- Size should be 57 x 57 pixels -->
    <%= favicon_link_tag 'apple-touch-icon-precomposed.png', :rel => 'apple-touch-icon-precomposed', :type => 'image/png' %>

    <!-- For all other devices -->
    <!-- Size should be 32 x 32 pixels -->
    <%= favicon_link_tag 'favicon.ico', :rel => 'shortcut icon' %>

    <%= javascript_include_tag "application" %>

    <!-- Le HTML5 shim, for IE6-8 support of HTML elements -->
    <!--[if lt IE 9]>
    <script src="//cdnjs.cloudflare.com/ajax/libs/html5shiv/3.7.2/html5shiv.min.js" type="text/javascript"></script>
    <![endif]-->
  </head>
  <body>

    <div class="navbar navbar-default navbar-static-top">
      <div class="container">
        <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-responsive-collapse">
          <span class="icon-bar"></span>
          <span class="icon-bar"></span>
          <span class="icon-bar"></span>
        </button>
        <a class="navbar-brand" href="#">Investing App</a>
        <div class="navbar-collapse collapse navbar-responsive-collapse">
          <ul class="nav navbar-nav">
            <li><%= link_to "Blog", "/path1"  %></li>
            <li><%= link_to "Link2", "/path2"  %></li>
            <li><%= link_to "Link3", "/path3"  %></li>
          </ul>
        </div>
      </div>
    </div>

    <div class="container">
      <div class="row">
        <div class="col-lg-9">
          <%= bootstrap_flash %>
          <%= yield %>
        </div>
      </div><!--/row-->

      <footer>
        <p>&copy; Company 2017</p>
      </footer>

    </div> <!-- /container -->

  </body>
</html>

app/views/stock/_lookup.html.erb
<div id="stock-lookup">
  <h3>Search for Stocks</h3>
  <%= form_tag search_stocks_path, remote: true, method: :get, id:'stock-lookup-form' do %>
    <div class="form-group row no-padding text-center cold-md-12">
      <div class="col-md-10">
        <%= text_field_tag :stock, params[:stock], placeholder: "Stock ticker symbol", autofocus: true,
                                                         class: "form-control search-box input-lg" %>
      </div>
      <div class="col-md-2">
        <%= button_tag(type: :submit, class: "btn btn-lg btn-success") do %>
          <span class="glyphicon glyphicon-search" aria-hidden="true"></span> Look up a Stock
        <% end %>
      </div>
    </div>
  <% end %>
  <%= render 'common/spinner' %>
  <% if @stock %>
    <div id="stock-lookup-results" class="well results-block">
      <table class="table table-hover">
        <tr>
          <td><strong>Symbol:</strong><%= @stock.ticker %></td>
          <td><strong>Name:</strong><%= @stock.name %></td>
          <td><strong>Current Price:</strong> $<%= @stock.current_price.round(2) %></td>
          <td><strong>One Year Estimate:</strong> $<%= @stock.one_year_estimate %></td>
          <td><strong>Estimated Return:</strong><%= @stock.percent_change.round(4) * 100 %>%</td>
        </tr>
        <p>
          According to the median analyst estimate, you could earn <strong>$<%=
          (@stock.one_year_estimate - @stock.current_price).round(2) %> per share</strong> if you bought it now <br>
          with an estimated return over the next year of <strong><%= @stock.percent_change.round(4) * 100%>%</strong>
        </p>
      </table>
    </div>
  <% end %>
  <div id="stock-lookup-errors"></div>
</div>

app/views/stock/_popular_stocks.html.erb
<h3>Popular Stocks</h3>
<table class="table table-hover">
  <thead class="thead-inverse">
      <th>Ticker</th>
      <th>Name</th>
      <th>Current Price</th>
      <th>One Year Estimate</th>
      <th>Estimated Return</th>
  </thead>
  <tr>
    <td>AAPL</td>
    <td>Apple</td>
    <td>$<%= Stock.new_stock_lookup("AAPL").current_price.round(2) %></td>
    <td>$<%= Stock.new_stock_lookup("AAPL").one_year_estimate %></td>
    <td><%= Stock.new_stock_lookup("AAPL").percent_change.round(4) * 100 %>%</td>
  </tr>
  <tr>
    <td>AMZN</td>
    <td>Amazon</td>
    <td>$<%= Stock.new_stock_lookup("AMZN").current_price.round(2) %></td>
    <td>$<%= Stock.new_stock_lookup("AMZN").one_year_estimate %></td>
    <td><%= Stock.new_stock_lookup("AMZN").percent_change.round(4) * 100 %>%</td>
  </tr>
  <tr>
    <td>TSLA</td>
    <td>Tesla</td>
    <td>$<%= Stock.new_stock_lookup("TSLA").current_price.round(2) %></td>
    <td>$<%= Stock.new_stock_lookup("TSLA").one_year_estimate %></td>
    <td><%= Stock.new_stock_lookup("TSLA").percent_change.round(4) * 100 %>%</td>
  </tr>
  <tr>
    <td>FB</td>
    <td>Facebook</td>
    <td>$<%= Stock.new_stock_lookup("FB").current_price.round(2) %></td>
    <td>$<%= Stock.new_stock_lookup("FB").one_year_estimate %></td>
    <td><%= Stock.new_stock_lookup("FB").percent_change.round(4) * 100 %>%</td>
  </tr>
  <tr>
    <td>MSFT</td>
    <td>Microsoft</td>
    <td>$<%= Stock.new_stock_lookup("MSFT").current_price.round(2) %></td>
    <td>$<%= Stock.new_stock_lookup("MSFT").one_year_estimate %></td>
    <td><%= Stock.new_stock_lookup("MSFT").percent_change.round(4) * 100 %>%</td>
  </tr>
  <tr>
    <td>DIS</td>
    <td>Disney</td>
    <td>$<%= Stock.new_stock_lookup("DIS").current_price.round(2) %></td>
    <td>$<%= Stock.new_stock_lookup("DIS").one_year_estimate %></td>
    <td><%= Stock.new_stock_lookup("DIS").percent_change.round(4) * 100 %>%</td>
  </tr>
  <tr>
    <td>BAC</td>
    <td>Bank Of America</td>
    <td>$<%= Stock.new_stock_lookup("BAC").current_price.round(2) %></td>
    <td>$<%= Stock.new_stock_lookup("BAC").one_year_estimate %></td>
    <td><%= Stock.new_stock_lookup("BAC").percent_change.round(4) * 100 %>%</td>
  </tr>
  <tr>
    <td>GOOG</td>
    <td>Alphabet</td>
    <td>$<%= Stock.new_stock_lookup("GOOG").current_price.round(2) %></td>
    <td>$<%= Stock.new_stock_lookup("GOOG").one_year_estimate %></td>
    <td><%= Stock.new_stock_lookup("GOOG").percent_change.round(4) * 100 %>%</td>
  </tr>
  <tr>
    <td>NFLX</td>
    <td>Netflix</td>
    <td>$<%= Stock.new_stock_lookup("NFLX").current_price.round(2) %></td>
    <td>$<%= Stock.new_stock_lookup("NFLX").one_year_estimate %></td>
    <td><%= Stock.new_stock_lookup("NFLX").percent_change.round(4) * 100 %>%</td>
  </tr>
  <tr>
    <td>BA</td>
    <td>Boeing</td>
    <td>$<%= Stock.new_stock_lookup("BA").current_price.round(2) %></td>
    <td>$<%= Stock.new_stock_lookup("BA").one_year_estimate %></td>
    <td><%= Stock.new_stock_lookup("BA").percent_change.round(4) * 100 %>%</td>
  </tr>

</table>

app/views/stock/index.html.erb
<h3>See which stocks can offer the best return based on analyst estimates!</h2>
<br>
<br>
<%= render 'stock/lookup' %>
<div class="container">
  <%= render 'stock/popular_stocks' %>
</div>